// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVl-mbEVuaqAIRoSz44r4_b7aS7YQSrbU',
    appId: '1:623201661056:web:7585026089070ca68b7665',
    messagingSenderId: '623201661056',
    projectId: 'craftly2026',
    authDomain: 'craftly2026.firebaseapp.com',
    storageBucket: 'craftly2026.firebasestorage.app',
    measurementId: 'G-KWPH8DPTTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcozUbrijQJq-8BePIR25We3OMlPgdvr0',
    appId: '1:623201661056:android:6f84047cd85d4f858b7665',
    messagingSenderId: '623201661056',
    projectId: 'craftly2026',
    storageBucket: 'craftly2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJPMsKcJVWptlPc6y1F2be85mS0-ACv4',
    appId: '1:623201661056:ios:0fa267dbc6d505828b7665',
    messagingSenderId: '623201661056',
    projectId: 'craftly2026',
    storageBucket: 'craftly2026.firebasestorage.app',
    iosBundleId: 'com.example.artisanGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJPMsKcJVWptlPc6y1F2be85mS0-ACv4',
    appId: '1:623201661056:ios:0fa267dbc6d505828b7665',
    messagingSenderId: '623201661056',
    projectId: 'craftly2026',
    storageBucket: 'craftly2026.firebasestorage.app',
    iosBundleId: 'com.example.artisanGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVl-mbEVuaqAIRoSz44r4_b7aS7YQSrbU',
    appId: '1:623201661056:web:618e504b83751e1b8b7665',
    messagingSenderId: '623201661056',
    projectId: 'craftly2026',
    authDomain: 'craftly2026.firebaseapp.com',
    storageBucket: 'craftly2026.firebasestorage.app',
    measurementId: 'G-RBYFDNM86Z',
  );
}
